version: "3.9"

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123!@#
      MYSQL_DATABASE: laptopshop
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  laptopshop:
    build: .
    container_name: laptopshop
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/laptopshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abc123!@#